### ISSUE TITLE
iFit.py

### ISSUE THREAD

**Issue by matt-varnam-volc** [ManchesterVolcanology/iFit#14]
Currently, the iFit.py example loads the dark spectrum but does not use it. 

Suggest change the Analyser creation (L88) to:

analyser = Analyser(params,
                    fit_window=[310, 320],
                    stray_flag=True,
                    stray_window=[280, 290], 
                    dark_flag=True,
                    frs_path='Ref/sao2010.txt')

This issue occurs because in spectral_analysis, the defaults are:

def __init__(self, params, fit_window, frs_path, model_padding=1.0,
                 model_spacing=0.01, flat_flag=False, flat_path=None,
                 stray_flag=False, stray_window=[280, 290], dark_flag=False,
                 ils_type='Manual', ils_path=None, despike_flag=False,
                 spike_limit=None, bad_pixels=None):

**Comment by benjaminesse** [comment]
Fixed in #368ebdc
