### ISSUE TITLE
GPS files sometimes fail to load

### ISSUE THREAD

**Issue by matt-varnam-volc** [ManchesterVolcanology/iFit#16]
I have an issue whereby some gps files that are identical to other gps files do not load.

C:\Users\Matt\Documents\Arizona\Software\iFit-main>python iFitUI.py
Traceback (most recent call last):
  File "C:\Users\Matt\Documents\Arizona\Software\iFit-main\ifit\gui_tools.py", line 577, in import_data
    gps_time = np.array([
                        ^
  File "C:\Users\Matt\Documents\Arizona\Software\iFit-main\ifit\gui_tools.py", line 578, in <listcomp>
    t.hour + t.minute/60 + t.second/3600 + tdiff
    ^^^^^^
AttributeError: 'str' object has no attribute 'hour'

The error arises because the line 569 in gui_tools.py can for some reason (that I haven't figured out) read in the date as a string rather than a datetime object (I have gps files that fail and gps files that work. Here is the offending line:

            gps_df = pd.read_table(
                self.widgets.get('gps_path'), sep='\t', parse_dates=['time']
            )

If after this line, the following addition is added, it should correct the error. 

            gps_df['time'] = pd.to_datetime(gps_df['time'], errors='coerce')

            # Check if there are any invalid values after conversion
            if gps_df['time'].isna().any():
                logger.info("Some time values couldn't be parsed:")
                logger.info(gps_df[gps_df['time'].isna()])

**Comment by benjaminesse** [comment]
Not sure what would be causing this, but I have added a check on reading in the GPS files to remove any rows with a NaN value in, hopefully that fixes the issue!

https://github.com/ManchesterVolcanology/iFit/commit/e98cde336d34e1d1e6da6b89354134d0aaf277ad

**Comment by benjaminesse** [comment]
This actually wasn't the issue, it was to do with mixed time format strings in the GPS file. Added an option to the reader to allow mixed time formats which has fixed this.

https://github.com/ManchesterVolcanology/iFit/commit/6b8828ab01835b3480750692ff6174446ceddede
